spring:
  application:
    name: spring-transaction
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/spring_transaction
    username: root
    password: toorroot
logging:
  level:
    org:
      apache:
        ibatis: debug
      mybatis: debug
      com:
        example:
          spring_transaction: debug
      springframework:
        transaction:
          interceptor: DEBUG
          support: DEBUG
    sql: debug
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.example.spring_transaction.**.entity